---
- name: Raspberry Pi Bookworm configuration
  hosts: local
  become: yes
  gather_facts: yes

  tasks:
    - name: Install essential packages
      apt:
        name:
          - git
          - curl
          - vim
          - htop
          - python3-pip
          - python3-venv
        state: present
        cache_valid_time: 2592000
        
    - name: Include Pi-specific tasks
      include_tasks: playbooks/raspberry-pi.yml

  post_tasks:
    - name: Log ansible-pull completion
      debug:
        msg: "Raspberry Pi configuration completed at {{ ansible_date_time.iso8601 }}"

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted

    - name: reload systemd
      systemd:
        daemon_reload: yes
      changed_when: false